version: '3.8'
services:
  task-manager:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      LOG_LEVEL: 20
    healthcheck:
      disable: true
      test:
        [
          'CMD-SHELL',
          'curl -s http://localhost:8000/check-health | grep ''"Not Found"''',
        ]
      interval: 2s
      timeout: 2s
      retries: 10
