version: '3.8'
services:
  task-manager:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    healthcheck:
      disable: true
      test: ['CMD-SHELL', 'curl -s http://localhost:${PORT}/check-health | grep ''"Not Found"''']
      interval: 2s
      timeout: 2s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
